name: no_ads_browser
description: A fast and minimal ad-blocking browser.
publish_to: 'none' # Private project, not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Ads
  google_mobile_ads: ^4.0.0

  # Preferences
  shared_preferences: ^2.2.2

  # Open external URLs (for PayPal donation, etc)
  url_launcher: ^6.2.5

  # Webview (adblock support via JS injection)
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static code analysis
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
