name: no_ads_browser
description: A fast and minimal ad-blocking browser.
publish_to: 'none' # Private project, not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Ads
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & best practices
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
